### ISSUE TITLE
Create new Logo for Font Blanche

### ISSUE THREAD

**Issue by Elweyn** [Elweyn/hello-world#2]
### Defintion
En tant qu'entreprise je nécessite une identité qui se montre par un Logo.

### Todos
- [x] Alena beauftragen ein Logo zu erstellen
- [x] [https://app.zenhub.com/files/108091818/4dfddc55-18c8-4b9c-9420-99db8b0156f3/download](https://app.zenhub.com/files/108091818/4dfddc55-18c8-4b9c-9420-99db8b0156f3/download)
- [ ] Alena feedback geben
